config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :pluggto_settings do
      get :upload_all_products
    end
    resources :products do
      resources :pluggto_fields, except: [:destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      namespace :pluggto, defaults: {format: :json} do
        post :notifications
      end
    end
  end

  # post "/pluggto/api/pluggto/notifications", to: 'api/v1/pluggto#notifications'
end

app/models/pluggto_settings.rb
class PluggtoSettings < ActiveRecord::Base
end

app/models/spree_pluggto/spree/product_decorator.rb
module SpreePluggto
  module Spree
    module ProductDecorator

      # https://guides.spreecommerce.org/developer/customization/logic.html
      # self.prepended is needed to access class-level methods, like has_many, scopes and callbacks
      def self.prepended(base)
        base.after_create :upsert_pluggto_product, if: :sync_with_pluggto?
        base.after_update :upsert_pluggto_product, if: :sync_with_pluggto?
      end

      private

      def upsert_pluggto_product
        ::SpreePluggto::UpsertProductJob.perform_later(self.id)
      end

    end
  end
end

Spree::Product.prepend(SpreePluggto::Spree::ProductDecorator)

app/models/spree_pluggto/spree/shipment_decorator.rb
module SpreePluggto
  module Spree
    module ShipmentDecorator

      # https://guides.spreecommerce.org/developer/customization/logic.html
      # self.prepended is needed to access class-level methods, like has_many, scopes and callbacks
      def self.prepended(base)
        base.state_machine.after_transition to: :shipped, do: :update_pluggto_order, if: :pluggto_order?
      end

      private

      def update_pluggto_order
        ::SpreePluggto::UpdatePluggtoOrderJob.perform_later(order.number)
      end

      def pluggto_order?
        order.channel == "pluggto"
      end
    end
  end
end

Spree::Shipment.prepend(SpreePluggto::Spree::ShipmentDecorator)

app/models/spree_pluggto/spree/stock_item_decorator.rb
module SpreePluggto
  module Spree
    module StockItemDecorator

      def self.prepended(base)
        base.after_save :update_pluggto_stock
      end

      private

      def update_pluggto_stock
        return unless product.sync_with_pluggto?
        ::SpreePluggto::UpdateStockJob.perform_later(variant_id)
      end
    end
  end
end

Spree::StockItem.prepend(SpreePluggto::Spree::StockItemDecorator)

app/controllers/spree/admin/pluggto_fields_controller.rb
module Spree
  module Admin
    class PluggtoFieldsController < ResourceController
      before_action :load_product

      def index
      end

      def update
      end 

      def location_after_save
        admin_product_pluggto_fields_url(@product)
      end

      private

      def load_product
        @product = Spree::Product.friendly.find(params[:product_id])
      end

      def model_class
        @model_class ||= Spree::Product
      end
    end
  end
end

app/controllers/spree/admin/pluggto_settings_controller.rb
module Spree
  module Admin
    class PluggtoSettingsController < Spree::Admin::BaseController
      before_action :set_pluggto_settings

      # Heavily inspired by SpreeMailchimpEcommerce
      # https://github.com/spree-contrib/spree_mailchimp_ecommerce
      # https://github.com/spree/spree/blob/master/backend/app/controllers/spree/admin/orders/customer_details_controller.rb

      def edit
      end

      def update
        @pluggto_settings.update(pluggto_settings_params)
        flash[:success] = Spree.t(:pluggto_settings_updated)
        redirect_to edit_admin_pluggto_settings_path
      end

      def upload_all_products
        ::SpreePluggto::UpsertAllProductsJob.perform_later
        flash[:success] = Spree.t(:pluggto_products_being_uploaded)
        redirect_to edit_admin_pluggto_settings_path
      end

      private

      def set_pluggto_settings
        @pluggto_settings = PluggtoSettings.first_or_create
      end

      def pluggto_settings_params
        params.require(:pluggto_settings).permit(:client_id,:client_secret,:username,:password)
      end
    end
  end
end

app/controllers/spree/api/v1/pluggto_controller.rb
module Spree
  module Api
    module V1
      class PluggtoController < Spree::Api::BaseController
        skip_before_action :authenticate_user

        # The post will be send in the following format:
        # {"type":"PRODUCTS/SKUS/ORDERS","id":"PLUGGTO_ID","action":"UPDATEORCREATE","user":1120, "changes" : {"status" : false,"stock" : false,"price":false }}
        #
        # Example:
        # { "user" : 129, "id" : "5b9169c309eacd415056aa3a", "changes" : { "status" : false, "stock" : false, "price" : false }, "type" : "products", "action" : "updated" }

        def notifications
          puts "Notification received from PluggTo: #{notification_params}"
          service_class = "spree_pluggto/#{notification_params[:type].singularize}_#{notification_params[:action]}_job".camelize
          puts "Service: #{service_class}"
          service_class.constantize.perform_later(notification_params[:id])
          head :ok
        end

        private

        def notification_params
          params.require(:pluggto).permit!
        end

      end
    end
  end
end

app/views/spree/admin/pluggto_fields/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :pluggto_fields } %>

<%= form_for [:admin, @product], method: :put do |f| %>

<fieldset>
  <div class="row">
    <div class="col-xs-12 col-md-8" data-hook="admin_product_pluggto_fields">
        <%= f.field_container :pluggto_id, class: ['form-group'] do %>
        <%= f.label :sync_with_pluggto, "Sincronizar com Plugg.to" %>
        <%= f.check_box :sync_with_pluggto %>
        <%= f.error_message_on :sync_with_pluggto %>
        <% end %>

        <%= f.field_container :pluggto_name, class: ['form-group'] do %>
        <%= f.label :pluggto_name, "Nome no Plugg.to" %>
        <%= f.text_field :pluggto_name, class: 'form-control', placeholder: "Deixe em branco para usar o nome original do produto" %>
        <%= f.error_message_on :pluggto_name %>
        <% end %>

        <%= f.field_container :pluggto_id, class: ['form-group'] do %>
        <%= f.label :pluggto_id, "ID no Plugg.to" %>
        <%= f.text_field :pluggto_id, class: 'form-control', readonly: true %>
        <%= f.error_message_on :pluggto_id %>
        <% end %>
    </div>
  </div>


  <%= render partial: 'spree/admin/shared/edit_resource_links' %>

</fieldset>

<% end %>

app/views/spree/admin/pluggto_settings/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:pluggto_settings) %>
<% end %>

<%= form_for @pluggto_settings, url: admin_pluggto_settings_path do |f| %>
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <div class="form-group" data-hook="admin_general_setting_input_name">
        <%= f.label :client_id, "client_id" %>
        <%= f.text_field :client_id, class: 'form-control' %>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="form-group" data-hook="admin_general_setting_input_seo_title">
        <%= f.label :client_secret, 'client_secret' %>
        <%= f.text_field :client_secret, class: 'form-control'  %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4">
      <div class="form-group" data-hook="admin_general_setting_input_name">
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="form-group" data-hook="admin_general_setting_input_seo_title">
        <%= f.label :password %>
        <%= f.text_field :password, class: 'form-control'  %>
      </div>
    </div>
  </div>

  <div class="form-actions" data-hook="buttons">
    <%= render partial: 'spree/admin/shared/edit_resource_links', locals: {collection_url: edit_admin_pluggto_settings_path} %>
  </div>
<% end %>


<div class="row" style="margin-top: 40px">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title"><%= Spree.t(:products) %></h1>
      </div>
      <div class="panel-body">
        <%= link_to Spree.t(:upload_all_products_to_pluggto), upload_all_products_admin_pluggto_settings_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>